module GoodreadsHelper
  def sample_data_of_books_fetched_from_goodreads_shelf
    [
      Hashie::Mash.new({
        "id"=>"2327186297",
        "book"=>
         {"id"=>3869,
          "isbn"=>"0553380168",
          "isbn13"=>"9780553380163",
          "text_reviews_count"=>4226,
          "uri"=>"kca://book/amzn1.gr.book.v1.tMtwVV4SCdc6-pqZtkrHOQ",
          "title"=>"A Brief History of Time",
          "title_without_series"=>"A Brief History of Time",
          "image_url"=>"https://images.gr-assets.com/books/1333578746m/3869.jpg",
          "small_image_url"=>"https://images.gr-assets.com/books/1333578746s/3869.jpg",
          "large_image_url"=>nil,
          "link"=>"https://www.goodreads.com/book/show/3869.A_Brief_History_of_Time",
          "num_pages"=>"212",
          "format"=>"Paperback",
          "edition_information"=>"Updated & Expanded 10th Anniversary",
          "publisher"=>"Bantam Books",
          "publication_day"=>"1",
          "publication_year"=>"1998",
          "publication_month"=>"9",
          "average_rating"=>"4.13",
          "ratings_count"=>"197598",
          "description"=>
           "In the ten years since its publication in 1988, Stephen Hawking's classic work has become a landmark volume in scientific writing, with more than nine million copies in forty languages sold worldwide. That edition was on the cutting edge of what was then known about the origins and nature of the universe. But the intervening years have seen extraordinary advances in the technology of observing both the micro- and the macrocosmic worlds. These observations have confirmed many of Professor Hawking's theoretical predictions in the first edition of his book, including the recent discoveries of the Cosmic Background Explorer satellite (COBE), which probed back in time to within 300,000 years of the universe's beginning and revealed wrinkles in the fabric of space-time that he had projected. Eager to bring to his original text the new knowledge revealed by these observations, as well as his own recent research, Professor Hawking has prepared a new introduction to the book, written an entirely new chapter on wormholes and time travel, and updated the chapters throughout.",
          "authors"=>
           {"author"=>
             {"id"=>"1401",
              "name"=>"Stephen Hawking",
              "role"=>nil,
              "image_url"=>"\nhttps://images.gr-assets.com/authors/1197404653p5/1401.jpg\n",
              "small_image_url"=>"\nhttps://images.gr-assets.com/authors/1197404653p2/1401.jpg\n",
              "link"=>"https://www.goodreads.com/author/show/1401.Stephen_Hawking",
              "average_rating"=>"4.11",
              "ratings_count"=>"362367",
              "text_reviews_count"=>"12466"}},
          "published"=>"1998",
          "work"=>{"id"=>"2192250", "uri"=>"kca://work/amzn1.gr.work.v1.OZ8CGI8cStk8Z7Qkqcry1g"}},
        "rating"=>"0",
        "votes"=>"0",
        "spoiler_flag"=>"false",
        "spoilers_state"=>"none",
        "shelves"=>{"shelf"=>{"exclusive"=>"true", "id"=>"000000000", "name"=>"to-read", "review_shelf_id"=>"0000000000", "sortable"=>"true"}},
        "recommended_for"=>nil,
        "recommended_by"=>nil,
        "started_at"=>nil,
        "read_at"=>nil,
        "date_added"=>"Wed Mar 14 05:54:36 -0700 2018",
        "date_updated"=>"Wed Mar 14 05:54:37 -0700 2018",
        "read_count"=>"0",
        "body"=>"\n  ",
        "comments_count"=>"0",
        "url"=>"https://www.goodreads.com/review/show/2327186297",
        "link"=>"https://www.goodreads.com/review/show/2327186297",
        "owned"=>"0"
      }),
      Hashie::Mash.new({
        "id"=>"2319445088",
        "book"=>
         {"id"=>36524697,
          "isbn"=>"1785783181",
          "isbn13"=>"9781785783180",
          "text_reviews_count"=>3,
          "uri"=>"kca://book/amzn1.gr.book.v1.fYHaCUne8AjAod0MGetQqQ",
          "title"=>"Testosterone Rex: Unmaking the Myths of Our Gendered Minds",
          "title_without_series"=>"Testosterone Rex: Unmaking the Myths of Our Gendered Minds",
          "image_url"=>"https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
          "small_image_url"=>"https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png",
          "large_image_url"=>nil,
          "link"=>"https://www.goodreads.com/book/show/36524697-testosterone-rex",
          "num_pages"=>nil,
          "format"=>nil,
          "edition_information"=>nil,
          "publisher"=>nil,
          "publication_day"=>nil,
          "publication_year"=>nil,
          "publication_month"=>nil,
          "average_rating"=>"3.75",
          "ratings_count"=>"807",
          "description"=>
           "Many people believe that, at its core, biological sex is a fundamental, diverging force in human development. According to this overly familiar story, differences between the sexes are shaped by past evolutionary pressures: Women are more cautious and parenting-focused, while men seek status to attract more mates. In each succeeding generation, sex hormones and male and female brains are thought to continue to reinforce these unbreachable distinctions, making for entrenched inequalities in modern society.<br /><br />In <i>Testosterone Rex</i>, psychologist Cordelia Fine wittily explains why past and present sex roles are only serving suggestions for the future, revealing a much more dynamic situation through an entertaining and well-documented exploration of the latest research that draws on evolutionary science, psychology, neuroscience, endocrinology, and philosophy. She uses stories from daily life, scientific research, and common sense to break through the din of cultural assumptions. Testosterone, for instance, is not the potent hormonal essence of masculinity; the presumed, built-in preferences of each sex, from toys to financial risk taking, are turned on their heads.<br /><br />Moving beyond the old “nature versus nurture” debates, <i>Testosterone Rex</i> disproves ingrained myths and calls for a more equal society based on both sexes’ full, human potential.",
          "authors"=>
           {"author"=>
             {"id"=>"204893",
              "name"=>"Cordelia Fine",
              "role"=>nil,
              "image_url"=>"\nhttps://images.gr-assets.com/authors/1271699438p5/204893.jpg\n",
              "small_image_url"=>"\nhttps://images.gr-assets.com/authors/1271699438p2/204893.jpg\n",
              "link"=>"https://www.goodreads.com/author/show/204893.Cordelia_Fine",
              "average_rating"=>"4.04",
              "ratings_count"=>"8759",
              "text_reviews_count"=>"969"}},
          "published"=>nil,
          "work"=>{"id"=>"50692501", "uri"=>"kca://work/amzn1.gr.work.v1.Wb_c7X3pJjKTDgi31mXP6Q"}},
        "rating"=>"0",
        "votes"=>"0",
        "spoiler_flag"=>"false",
        "spoilers_state"=>"none",
        "shelves"=>{"shelf"=>{"exclusive"=>"true", "id"=>"000000000", "name"=>"to-read", "review_shelf_id"=>"0000000000", "sortable"=>"true"}},
        "recommended_for"=>nil,
        "recommended_by"=>nil,
        "started_at"=>"Wed Mar 07 01:27:19 -0800 2018",
        "read_at"=>nil,
        "date_added"=>"Wed Mar 07 01:27:18 -0800 2018",
        "date_updated"=>"Wed Mar 07 01:27:19 -0800 2018",
        "read_count"=>"0",
        "body"=>"\n  ",
        "comments_count"=>"0",
        "url"=>"https://www.goodreads.com/review/show/2319445088",
        "link"=>"https://www.goodreads.com/review/show/2319445088",
        "owned"=>"0"
      }),
      Hashie::Mash.new({
        "id"=>"2304847024",
        "book"=>
         {"id"=>13598053,
          "isbn"=>"0674065859",
          "isbn13"=>"9780674065857",
          "text_reviews_count"=>70,
          "uri"=>"kca://book/amzn1.gr.book.v1.-gTtF2TPfTiIOv9Um9uLnA",
          "title"=>"Internal Time: Chronotypes, Social Jet Lag, and Why You're So Tired",
          "title_without_series"=>"Internal Time: Chronotypes, Social Jet Lag, and Why You're So Tired",
          "image_url"=>"https://images.gr-assets.com/books/1334176383m/13598053.jpg",
          "small_image_url"=>"https://images.gr-assets.com/books/1334176383s/13598053.jpg",
          "large_image_url"=>nil,
          "link"=>"https://www.goodreads.com/book/show/13598053-internal-time",
          "num_pages"=>"288",
          "format"=>"Hardcover",
          "edition_information"=>nil,
          "publisher"=>"Harvard University Press",
          "publication_day"=>nil,
          "publication_year"=>"2012",
          "publication_month"=>"4",
          "average_rating"=>"3.69",
          "ratings_count"=>"506",
          "description"=>
           "Early birds and night owls are born, not made. Sleep patterns may be the most obvious manifestation of the highly individualized biological clocks we inherit, but these clocks also regulate bodily functions from digestion to hormone levels to cognition. Living at odds with our internal timepieces, Till Roenneberg shows, can make us chronically sleep deprived and more likely to smoke, gain weight, feel depressed, fall ill, and fail geometry. By understanding and respecting our internal time, we can live better.<br /><br />Internal Time combines storytelling with accessible science tutorials to explain how our internal clocks work—for example, why morning classes are so unpopular and why “lazy” adolescents are wise to avoid them. We learn why the constant twilight of our largely indoor lives makes us dependent on alarm clocks and tired, and why social demands and work schedules lead to a social jet lag that compromises our daily functioning.<br /><br />Many of the factors that make us early or late “chronotypes” are beyond our control, but that doesn’t make us powerless. Roenneberg recommends that the best way to sync our internal time with our external environment and feel better is to get more sunlight. Such simple steps as cycling to work and eating breakfast outside may be the tickets to a good night’s sleep, better overall health, and less grouchiness in the morning.<br /><br />[Description taken from publisher's web site.]",
          "authors"=>
           {"author"=>
             {"id"=>"4407514",
              "name"=>"Till Roenneberg",
              "role"=>nil,
              "image_url"=>"\nhttps://s.gr-assets.com/assets/nophoto/user/m_200x266-d279b33f8eec0f27b7272477f09806be.png\n",
              "small_image_url"=>"\nhttps://s.gr-assets.com/assets/nophoto/user/m_50x66-82093808bca726cb3249a493fbd3bd0f.png\n",
              "link"=>"https://www.goodreads.com/author/show/4407514.Till_Roenneberg",
              "average_rating"=>"3.69",
              "ratings_count"=>"507",
              "text_reviews_count"=>"73"}},
          "published"=>"2012",
          "work"=>{"id"=>"19188400", "uri"=>"kca://work/amzn1.gr.work.v1.zzHZwUIBJZ-ybKDqS4oSEQ"}},
        "rating"=>"0",
        "votes"=>"0",
        "spoiler_flag"=>"false",
        "spoilers_state"=>"none",
        "shelves"=>{"shelf"=>{"exclusive"=>"true", "id"=>"000000000", "name"=>"to-read", "review_shelf_id"=>"0000000000", "sortable"=>"true"}},
        "recommended_for"=>nil,
        "recommended_by"=>nil,
        "started_at"=>nil,
        "read_at"=>nil,
        "date_added"=>"Thu Feb 22 10:01:49 -0800 2018",
        "date_updated"=>"Thu Feb 22 10:01:50 -0800 2018",
        "read_count"=>"0",
        "body"=>"\n  ",
        "comments_count"=>"0",
        "url"=>"https://www.goodreads.com/review/show/2304847024",
        "link"=>"https://www.goodreads.com/review/show/2304847024",
        "owned"=>"0"
      })
    ]
  end
end
